-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgZuuSJTqxgGL/FABX
nJxUJ+4bEY1d4rOcDrR16f8a1NmgCgYIKoZIzj0DAQehRANCAARg9rLjJBGWWM/5
kQjXypatEnLK4XP/iayUb0LHfueNFXaFC4GLP/XeHjCjMBG8mDr5aLiH0R/qd2Xg
RCxdzxiW
-----END PRIVATE KEY-----